---
- hosts: junos 
  gather_facts: no
  connection: local

  tasks:
    - name: include credential
      include_vars: 
        file: ./credential.yml
    - name: backup
      junos_config: 
        backup: yes
        provider: "{{ cli }}"

  vars:
    cli:   
      host:     "{{ ansible_host }}"   
      username: "{{ ansible_user }}"     
      password: "{{ ansible_password }}"
